# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /home/ishank/Documents/Unreal Engine
GAMEPROJECTFILE =/run/media/ishank/Work/Projects/Unreal Engine/Project A24/ProjectA24.uproject

TARGETS = \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Shipping  \
	UnrealEditor \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Shipping  \
	UnrealGame \
	ProjectA24-Linux-DebugGame  \
	ProjectA24-Linux-Shipping  \
	ProjectA24 \
	ProjectA24Editor-Linux-DebugGame  \
	ProjectA24Editor-Linux-Shipping  \
	ProjectA24Editor\
	configure

BUILD = bash "$(UNREALROOTPATH)/Engine/Build/BatchFiles/Linux/Build.sh"
PROJECTBUILD = "$(UNREALROOTPATH)/Engine/Binaries/ThirdParty/DotNet/6.0.302/linux/dotnet" "$(UNREALROOTPATH)/Engine/Binaries/DotNET/UnrealBuildTool/UnrealBuildTool.dll"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend ProjectA24Editor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug ProjectA24Editor-Linux-Debug


UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  $(ARGS)

UnrealEditor-Linux-Shipping:
	 $(BUILD) UnrealEditor Linux Shipping  $(ARGS)

UnrealEditor:
	 $(BUILD) UnrealEditor Linux Development  $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  $(ARGS)

UnrealGame:
	 $(BUILD) UnrealGame Linux Development  $(ARGS)

ProjectA24-Linux-DebugGame:
	 $(PROJECTBUILD) ProjectA24 Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

ProjectA24-Linux-Shipping:
	 $(PROJECTBUILD) ProjectA24 Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

ProjectA24:
	 $(PROJECTBUILD) ProjectA24 Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

ProjectA24Editor-Linux-DebugGame:
	 $(PROJECTBUILD) ProjectA24Editor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

ProjectA24Editor-Linux-Shipping:
	 $(PROJECTBUILD) ProjectA24Editor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

ProjectA24Editor:
	 $(PROJECTBUILD) ProjectA24Editor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

configure:
	xbuild /property:Configuration=Development /verbosity:quiet /nologo "$(UNREALROOTPATH)/Engine/Source/Programs/UnrealBuildTool/UnrealBuildTool.csproj"
	$(PROJECTBUILD) -projectfiles -project="\"$(GAMEPROJECTFILE)\"" -game -engine 

.PHONY: $(TARGETS)
