# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /home/ishank/Documents/Unreal Engine
GAMEPROJECTFILE =/home/ishank/Unreal Projects/Project_A23/Project_A23.uproject

TARGETS = \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Shipping  \
	UnrealEditor \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Shipping  \
	UnrealGame \
	Project_A23-Linux-DebugGame  \
	Project_A23-Linux-Shipping  \
	Project_A23 \
	Project_A23Editor-Linux-DebugGame  \
	Project_A23Editor-Linux-Shipping  \
	Project_A23Editor\
	configure

BUILD = bash "$(UNREALROOTPATH)/Engine/Build/BatchFiles/Linux/Build.sh"
PROJECTBUILD = "$(UNREALROOTPATH)/Engine/Binaries/ThirdParty/DotNet/6.0.302/linux/dotnet" "$(UNREALROOTPATH)/Engine/Binaries/DotNET/UnrealBuildTool/UnrealBuildTool.dll"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend Project_A23Editor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug Project_A23Editor-Linux-Debug


UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  $(ARGS)

UnrealEditor-Linux-Shipping:
	 $(BUILD) UnrealEditor Linux Shipping  $(ARGS)

UnrealEditor:
	 $(BUILD) UnrealEditor Linux Development  $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  $(ARGS)

UnrealGame:
	 $(BUILD) UnrealGame Linux Development  $(ARGS)

Project_A23-Linux-DebugGame:
	 $(PROJECTBUILD) Project_A23 Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

Project_A23-Linux-Shipping:
	 $(PROJECTBUILD) Project_A23 Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

Project_A23:
	 $(PROJECTBUILD) Project_A23 Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

Project_A23Editor-Linux-DebugGame:
	 $(PROJECTBUILD) Project_A23Editor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

Project_A23Editor-Linux-Shipping:
	 $(PROJECTBUILD) Project_A23Editor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

Project_A23Editor:
	 $(PROJECTBUILD) Project_A23Editor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

configure:
	xbuild /property:Configuration=Development /verbosity:quiet /nologo "$(UNREALROOTPATH)/Engine/Source/Programs/UnrealBuildTool/UnrealBuildTool.csproj"
	$(PROJECTBUILD) -projectfiles -project="\"$(GAMEPROJECTFILE)\"" -game -engine 

.PHONY: $(TARGETS)
